### ISSUE TITLE
Lower-resolution bloom

### ISSUE THREAD

**Issue by jonas-schievink** [OsnaCS/plantex#138]
We're apparently blurring the bloom texture 20 times in a row. We should try to use a lower-resolution bloom texture and blur that just once. Reducing the loop to only blur once (in each direction) noticably improves performance on my desktop (GTX 770) - From about 40 to more than 60 FPS.

Marking as `P-high` since we really need to get our performance under control :/

**Comment by LukasKalbertodt** [comment]
Absolutely! This is already on the private queue of the post processing team :wink: 

I also planned to use a little trick to half the texture fetches, which should pretty much double the blur speed since blur is a very texture heavy operation. But: on the CIP-PCs I measured a different performance impact... there it only took about 1/6 of the total time (or even less). But we'll see!
